BookATable/ViewModels/Reservations/ReservationsCreateViewModel.cs
using BookATable.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookATable.ViewModels.Reservations
{
    public class ReservationsCreateViewModel
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public int RestaurantId { get; set; }
        public int PeopleCount { get; set; }

        [Required(ErrorMessage = "Please input a Reservation Time! It is required!")]
        [DataType(DataType.Date)]

        public DateTime ReservationTime { get; set; }
        public string Comment { get; set; }
        public List<SelectListItem> Users { get; set; }
        public List<SelectListItem> Restaurants { get; set; }
    }
}

BookATable/ViewModels/Reservations/ReservationsDeleteViewModel.cs
using BookATable.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookATable.ViewModels.Reservations
{
    public class ReservationsDeleteViewModel:BaseEntity
    {
        public int UserId { get; set; }
        public int RestaurantId { get; set; }
        public int PeopleCount { get; set; }
        public DateTime ReservationTime { get; set; }
        public string Comment { get; set; }
    }
}

BookATable/ViewModels/Reservations/ReservationsEditViewModel.cs
using BookATable.Entity;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookATable.ViewModels.Reservations
{
    public class ReservationsEditViewModel:BaseEntity
    {
        public int UserId { get; set; }
        public int RestaurantId { get; set; }
        public int PeopleCount { get; set; }
        [Required(ErrorMessage = "Please input a Reservation Time! It is required!")]
        public DateTime ReservationTime { get; set; }
        public string Comment { get; set; }
        public List<SelectListItem> Users { get; set; }
        public List<SelectListItem> Restaurants { get; set; }
    }
}

BookATable/ViewModels/Reservations/ReservationsListViewModel.cs
using BookATable.Entity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BookATable.ViewModels.Reservations
{
    public class ReservationsListViewModel
    {
        public List<Reservation> Reservations { get; set; }
    }
}

BookATable/Controllers/ReservationController.cs
using BookATable.Data.Repositories;
using BookATable.Entity;
using BookATable.Filters;
using BookATable.ViewModels.Reservations;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BookATable.Controllers
{
    [AuthenticationFilter(RequireAdminRole = false)]
    public class ReservationController : Controller
    {
        public ActionResult Index()
        {
            ReservationRepository repository = new ReservationRepository();
            List<Reservation> reservations = repository.GetAll();

            ReservationsListViewModel model = new ReservationsListViewModel();
            model.Reservations = reservations;

            return View(model);
        }

        public ActionResult Create()
        {
            ReservationsCreateViewModel model = new ReservationsCreateViewModel();
            model.Restaurants = PopulateRestaurantsList();
            model.Users = PopulateUsersList();
            model.PeopleCount = model.PeopleCount;
            model.ReservationTime = model.ReservationTime.Date;
            model.Comment = model.Comment;


            return View(model);
        }

        private List<SelectListItem> PopulateUsersList()
        {
            List<SelectListItem> result = new List<SelectListItem>();
            UserRepository userRepo = new UserRepository();
            List<User> users = userRepo.GetAll();
            foreach (User user in users)
            {
                SelectListItem item = new SelectListItem();
                item.Value = user.ID.ToString();
                item.Text = $"{user.Name}";

                result.Add(item);
            }

            return result;
        }

        private List<SelectListItem> PopulateRestaurantsList()
        {
            List<SelectListItem> result = new List<SelectListItem>();
            RestaurantRepository restaurantRepo = new RestaurantRepository();
            List<Restaurant> restaurants = restaurantRepo.GetAll();
            foreach (Restaurant restaurant in restaurants)
            {
                SelectListItem item = new SelectListItem();
                item.Value = restaurant.ID.ToString();
                item.Text = $"{restaurant.Name}";

                result.Add(item);
            }

            return result;
        }

        [HttpPost]
        public ActionResult Create(ReservationsCreateViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            Reservation reservation = new Reservation();
            reservation.UserId = model.UserId;
            reservation.RestaurantId = model.RestaurantId;
            reservation.PeopleCount = model.PeopleCount;
            reservation.ReservationTime = model.ReservationTime.Date;
            reservation.Comment = model.Comment;
            
            var repository = new ReservationRepository();
            repository.Insert(reservation);

            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int? id)
        {

            ReservationRepository repository = new ReservationRepository();

            ReservationsEditViewModel model = new ReservationsEditViewModel();

            if (id.HasValue)
            {
                Reservation reservation = repository.GetByID(id.Value);
                model.ID = reservation.ID;
                model.Users = PopulateUsersList();
                model.Restaurants = PopulateRestaurantsList();
                model.PeopleCount = model.PeopleCount;
                model.ReservationTime = model.ReservationTime.Date;
                model.Comment = model.Comment;

            }

            return View(model);
        }


        [HttpPost]
        public ActionResult Edit(ReservationsEditViewModel model)
        {

            if (!ModelState.IsValid)
            {
                return View(model);
            }

            ReservationRepository repository = new ReservationRepository();

            Reservation reservation = new Reservation();
            reservation.ID = model.ID;
            reservation.UserId = model.UserId;
            reservation.RestaurantId = model.RestaurantId;
            reservation.PeopleCount = model.PeopleCount;
            reservation.ReservationTime = model.ReservationTime;
            reservation.Comment = model.Comment;


            repository.Save(reservation);

            return RedirectToAction("Index");
        }



        [HttpGet]
        public ActionResult Delete(int id)
        {

            ReservationRepository repository = new ReservationRepository();

            Reservation reservation = repository.GetByID(id);

            ReservationsDeleteViewModel model = new ReservationsDeleteViewModel();
            model.ID = reservation.ID;
            model.UserId = reservation.UserId;
            model.RestaurantId = reservation.RestaurantId;
            model.ReservationTime = reservation.ReservationTime;
            model.PeopleCount = reservation.PeopleCount;
            model.Comment = reservation.Comment;

            return View(model);
        }

        [HttpPost]
        public ActionResult Delete(ReservationsDeleteViewModel model)
        {

            ReservationRepository repository = new ReservationRepository();

            repository.Delete(model.ID);

            return RedirectToAction("Index");
        }

    }
}

BookATable/Views/Reservation/Create.cshtml
@model BookATable.ViewModels.Reservations.ReservationsCreateViewModel
@{
    ViewBag.Title = "Make a Reservation";
}

<style>
    body {
        background-color: sandybrown;
    }

    p {
        color: black;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h3 style="text-align:center;">Reservation</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @*@Html.HiddenFor(model => model.ID)*@

        <div class="form-group" style="margin-left:240px">
            @Html.LabelFor(model => model.Restaurants, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    <select name="RestaurantId" id="restaurants" class="form-control col-md-offset">
                        @foreach (var item in Model.Restaurants)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>
        </div>

        <div class="form-group" style="margin-left:240px">
            @Html.LabelFor(model => model.Users, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    <select name="UserId" id="users" class="form-control">
                        @foreach (var item in Model.Users)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>
        </div>

        <div class="form-group" style="margin-left:240px">
            @Html.LabelFor(model => model.PeopleCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PeopleCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PeopleCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-left:240px">
            @Html.LabelFor(model => model.ReservationTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReservationTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReservationTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-left:240px">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group" style="margin-left:350px">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success;" style="background-color:#F4511E; color: white; border:none" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to Reservations", "Index")
</div>

BookATable/Views/Reservation/Delete.cshtml
@model BookATable.ViewModels.Reservations.ReservationsDeleteViewModel

<style>
    body {
        background-color: sandybrown;
    }

    p {
        color: black;
    }
</style>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Reservation</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ReservationTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReservationTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PeopleCount)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PeopleCount)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Comment)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Comment)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

BookATable/Views/Reservation/Edit.cshtml
@model BookATable.ViewModels.Reservations.ReservationsEditViewModel

<style>
    body {
        background-color: sandybrown;
    }

    p {
        color: black;
    }
</style>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Reservation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)


        <div class="form-group">
            @Html.LabelFor(model => model.Restaurants, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    <select name="RestaurantId" id="restaurants" class="form-control col-md-offset">
                        @foreach (var item in Model.Restaurants)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Users, htmlAttributes: new { @class = "control-label col-md-2" })
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="col-md-10">
                    <select name="UserId" id="users" class="form-control col-md-offset">
                        @foreach (var item in Model.Users)
                        {
                            <option value="@item.Value">@item.Text</option>
                        }
                    </select>
                </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.PeopleCount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PeopleCount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PeopleCount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ReservationTime, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ReservationTime, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ReservationTime, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Comment, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Comment, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Comment, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BookATable/Views/Reservation/Index.cshtml
@model BookATable.ViewModels.Reservations.ReservationsListViewModel
@{
    ViewBag.Title = "Reservations";
}

<head>
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">

    <style>
        .table th {
            text-align: center;
            color: white;
            font-family: Montserrat, sans-serif;
        }

        .table td {
            text-align: center;
            color: black;
        }

        body {
            background-color: sandybrown;
        }
    </style>
</head>

<h2 style="text-align:center;">Reservations</h2>

@Html.ActionLink("Create new", "Create", "Reservation", new { @class = "btn btn-info", @style = "background-color: #F4511E; border: none" })

<hr />

<table class="table">
    <thead style="background-color: #F4511E;">
        <tr>
            <th>User</th>
            <th>Restaurant</th>
            <th>Reservation Time</th>
            <th>People Count</th>
            <th>Comment</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var reservation in Model.Reservations)
        {
            <tr>
                <td>@reservation.User.Name</td>
                <td>@reservation.Restaurant.Name</td>
                <td>@reservation.ReservationTime</td>
                <td>@reservation.PeopleCount</td>
                <td>@reservation.Comment</td>
                

                @{
                    if (BookATable.Filters.AdminFilter.IsAdmin())
                    {
                        <td>@Html.ActionLink("Edit", "Edit", "Reservation", new { id = reservation.ID }, new { @class = "btn btn-success glypchicon glyphicon-pencil" })</td>
                        <td>@Html.ActionLink("Delete", "Delete", "Reservation", new { id = reservation.ID }, new { @class = "btn btn-danger" })</td>
                    }
                }
            </tr>
        }
    </tbody>
</table>